main: com.subtextgroup.mcp.ospark.OldSparky
name: OldSparky
version: 1.0
author: ryanjohnson
description: Electrocution for Minecraft
commands:
  oldsparky:
    description: Makes target block an OldSparky spark target
    usage: /oldsparky [number of strikes, 1-10]
    permission: oldsparky.oldsparky
    permission-message: You don't have the oldsparky.oldsparky permission!
  